/**
 * Demo data.
 *
 * Realistic for the Kenyan market: real counties, plausible names across
 * communities, sectors that actually hire (BPO, e-commerce, logistics, agri,
 * fintech, hospitality), and salary bands that reflect what these roles pay.
 *
 * Everything created from this file is flagged `is_demo = true` and rendered
 * with a "Demo data" marker, so nobody can mistake it for a real person,
 * employer, or vacancy.
 */

export interface DemoWorker {
  fullName: string;
  email: string;
  phone: string;
  county: string;
  town: string;
  ageBracket: string;
  education: string;
  fieldOfStudy?: string;
  yearsExperience: number;
  employmentStatus: string;
  languages: string[];
  headline: string;
  summary: string;
  interests: string[];
  hasLaptop: boolean;
  internetAccess: string;
  desiredIncomeKes: number;
  workArrangement: string;
  preferredWorkTypes: string[];
  skills: Array<{ slug: string; level: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED' | 'EXPERT' }>;
  /** Simulation slugs this worker has passed, with their score. */
  provenSimulations?: Array<{ slug: string; score: number }>;
  openToDiscovery?: boolean;
  cvText?: string;
}

export const DEMO_WORKERS: DemoWorker[] = [
  {
    fullName: 'Grace Wanjiru',
    email: 'demo-worker@example.com',
    phone: '+254712000001',
    county: 'Nairobi',
    town: 'Kasarani',
    ageBracket: '25-34',
    education: 'DIPLOMA',
    fieldOfStudy: 'Business Administration',
    yearsExperience: 3,
    employmentStatus: 'UNDEREMPLOYED',
    languages: ['en', 'sw', 'ki'],
    headline: 'Customer support agent with verified data cleaning and Excel',
    summary:
      'Three years handling customer enquiries for an e-commerce company, mostly by chat and phone. I am organised, I keep good records, and I am comfortable working with spreadsheets. Looking for remote or Nairobi-based support or data work.',
    interests: ['customer service', 'data', 'remote work'],
    hasLaptop: true,
    internetAccess: 'BROADBAND',
    desiredIncomeKes: 45_000,
    workArrangement: 'ANY',
    preferredWorkTypes: ['FULL_TIME', 'CONTRACT', 'GIG'],
    skills: [
      { slug: 'customer-support', level: 'ADVANCED' },
      { slug: 'excel', level: 'ADVANCED' },
      { slug: 'data-entry-cleaning', level: 'INTERMEDIATE' },
      { slug: 'written-communication', level: 'ADVANCED' },
      { slug: 'complaint-handling', level: 'INTERMEDIATE' },
      { slug: 'english-proficiency', level: 'ADVANCED' },
      { slug: 'swahili-proficiency', level: 'EXPERT' },
    ],
    provenSimulations: [
      { slug: 'cs-difficult-customer', score: 84 },
      { slug: 'data-spreadsheet-clean', score: 79 },
    ],
    cvText: `Grace Wanjiru
Nairobi, Kenya | +254 712 000 001 | grace.wanjiru@example.com

EXPERIENCE
Customer Service Agent at Sokoni Online, 2022 - present
- Handled 60+ customer enquiries daily across chat, email and phone
- Reduced average first-response time from 4 hours to 45 minutes
- Maintained the returns tracking spreadsheet for the whole team

Sales Assistant at Westgate Retail, 2021 - 2022
- Served customers on the shop floor and reconciled daily till records

EDUCATION
Diploma in Business Administration, Kenya Institute of Management, 2019 - 2021

SKILLS
Customer support, Microsoft Excel, data entry, English, Kiswahili, Kikuyu`,
  },
  {
    fullName: 'Brian Otieno',
    email: 'brian.otieno@demo.kazios.co.ke',
    phone: '+254712000002',
    county: 'Kisumu',
    town: 'Milimani',
    ageBracket: '18-24',
    education: 'BACHELORS',
    fieldOfStudy: 'Information Technology',
    yearsExperience: 1,
    employmentStatus: 'UNEMPLOYED',
    languages: ['en', 'sw', 'luo'],
    headline: 'Recent IT graduate looking for a first role in tech support or web',
    summary:
      'Graduated last year with an IT degree. I built two websites for local businesses during my attachment and I am comfortable with HTML, CSS and basic JavaScript. I learn fast and I am looking for a first real role.',
    interests: ['web development', 'IT support', 'technology'],
    hasLaptop: true,
    internetAccess: 'MOBILE_DATA',
    desiredIncomeKes: 35_000,
    workArrangement: 'ANY',
    preferredWorkTypes: ['FULL_TIME', 'INTERNSHIP', 'GIG'],
    skills: [
      { slug: 'html-css', level: 'INTERMEDIATE' },
      { slug: 'javascript', level: 'BEGINNER' },
      { slug: 'it-support', level: 'INTERMEDIATE' },
      { slug: 'wordpress', level: 'INTERMEDIATE' },
      { slug: 'problem-solving', level: 'INTERMEDIATE' },
    ],
    provenSimulations: [{ slug: 'written-communication-brief', score: 71 }],
  },
  {
    fullName: 'Fatuma Hassan',
    email: 'fatuma.hassan@demo.kazios.co.ke',
    phone: '+254712000003',
    county: 'Mombasa',
    town: 'Nyali',
    ageBracket: '25-34',
    education: 'CERTIFICATE',
    yearsExperience: 5,
    employmentStatus: 'SELF_EMPLOYED',
    languages: ['en', 'sw', 'ar'],
    headline: 'Social media manager for small businesses on the coast',
    summary:
      'I have run social media for four hotels and two restaurants in Mombasa. I write the captions, design the posts in Canva, and handle the DMs. I want more clients, ideally on retainer.',
    interests: ['social media', 'design', 'hospitality'],
    hasLaptop: true,
    internetAccess: 'BROADBAND',
    desiredIncomeKes: 60_000,
    workArrangement: 'REMOTE',
    preferredWorkTypes: ['CONTRACT', 'GIG', 'PART_TIME'],
    skills: [
      { slug: 'social-media-management', level: 'ADVANCED' },
      { slug: 'caption-writing', level: 'ADVANCED' },
      { slug: 'canva', level: 'ADVANCED' },
      { slug: 'content-calendar', level: 'INTERMEDIATE' },
      { slug: 'social-analytics', level: 'INTERMEDIATE' },
    ],
    provenSimulations: [
      { slug: 'smm-campaign-plan', score: 88 },
      { slug: 'smm-captions', score: 82 },
    ],
  },
  {
    fullName: 'Peter Kimani',
    email: 'peter.kimani@demo.kazios.co.ke',
    phone: '+254712000004',
    county: 'Kiambu',
    town: 'Ruiru',
    ageBracket: '35-44',
    education: 'SECONDARY',
    yearsExperience: 12,
    employmentStatus: 'CASUAL_WORKER',
    languages: ['en', 'sw', 'ki'],
    headline: 'Twelve years in stores and logistics, now looking for steady work',
    summary:
      'I have worked in warehouses and stores since 2013 — receiving goods, stock counts, dispatch records. Most of it was casual so I have no certificates, but I know the work.',
    interests: ['logistics', 'stores', 'operations'],
    hasLaptop: false,
    internetAccess: 'MOBILE_DATA',
    desiredIncomeKes: 30_000,
    workArrangement: 'ONSITE',
    preferredWorkTypes: ['FULL_TIME', 'CASUAL', 'CONTRACT'],
    skills: [
      { slug: 'inventory-management', level: 'ADVANCED' },
      { slug: 'logistics-coordination', level: 'INTERMEDIATE' },
      { slug: 'data-entry', level: 'INTERMEDIATE' },
      { slug: 'attention-to-detail', level: 'ADVANCED' },
    ],
    openToDiscovery: true,
  },
  {
    fullName: 'Mercy Akinyi',
    email: 'mercy.akinyi@demo.kazios.co.ke',
    phone: '+254712000005',
    county: 'Nairobi',
    town: 'Embakasi',
    ageBracket: '25-34',
    education: 'BACHELORS',
    fieldOfStudy: 'Commerce (Accounting)',
    yearsExperience: 4,
    employmentStatus: 'EMPLOYED_FULL_TIME',
    languages: ['en', 'sw'],
    headline: 'Accounts assistant — reconciliation, QuickBooks, monthly reporting',
    summary:
      'I handle bookkeeping and reconciliation for a mid-size distributor. Looking for part-time bookkeeping work for small businesses alongside my job.',
    interests: ['bookkeeping', 'finance', 'part-time work'],
    hasLaptop: true,
    internetAccess: 'BROADBAND',
    desiredIncomeKes: 40_000,
    workArrangement: 'REMOTE',
    preferredWorkTypes: ['PART_TIME', 'GIG', 'CONTRACT'],
    skills: [
      { slug: 'bookkeeping', level: 'ADVANCED' },
      { slug: 'accounts-reconciliation', level: 'ADVANCED' },
      { slug: 'quickbooks', level: 'INTERMEDIATE' },
      { slug: 'excel', level: 'ADVANCED' },
      { slug: 'financial-reporting', level: 'INTERMEDIATE' },
    ],
    provenSimulations: [
      { slug: 'book-reconciliation', score: 91 },
      { slug: 'book-transaction-classification', score: 86 },
    ],
  },
  {
    fullName: 'Dennis Mutua',
    email: 'dennis.mutua@demo.kazios.co.ke',
    phone: '+254712000006',
    county: 'Machakos',
    town: 'Machakos Town',
    ageBracket: '18-24',
    education: 'SECONDARY',
    yearsExperience: 0,
    employmentStatus: 'UNEMPLOYED',
    languages: ['en', 'sw', 'kam'],
    headline: 'Looking for my first job — willing to learn',
    summary:
      'I finished secondary school two years ago. I have helped in my uncle\'s shop with stock and M-Pesa, but I have never had a formal job. I am not sure what I am qualified for.',
    interests: ['anything', 'learning'],
    hasLaptop: false,
    internetAccess: 'MOBILE_DATA',
    desiredIncomeKes: 20_000,
    workArrangement: 'ANY',
    preferredWorkTypes: ['CASUAL', 'GIG', 'FULL_TIME'],
    skills: [{ slug: 'swahili-proficiency', level: 'EXPERT' }],
    openToDiscovery: true,
  },
  {
    fullName: 'Sharon Chebet',
    email: 'sharon.chebet@demo.kazios.co.ke',
    phone: '+254712000007',
    county: 'Uasin Gishu',
    town: 'Eldoret',
    ageBracket: '25-34',
    education: 'DIPLOMA',
    fieldOfStudy: 'Journalism',
    yearsExperience: 3,
    employmentStatus: 'UNDEREMPLOYED',
    languages: ['en', 'sw'],
    headline: 'Content writer — blogs, product copy and research',
    summary:
      'I write blog articles and product descriptions for agencies. Fast, clean copy with proper research. I want steady remote writing work.',
    interests: ['writing', 'research', 'marketing'],
    hasLaptop: true,
    internetAccess: 'BROADBAND',
    desiredIncomeKes: 50_000,
    workArrangement: 'REMOTE',
    preferredWorkTypes: ['CONTRACT', 'GIG', 'PART_TIME'],
    skills: [
      { slug: 'content-writing', level: 'ADVANCED' },
      { slug: 'research', level: 'ADVANCED' },
      { slug: 'seo', level: 'INTERMEDIATE' },
      { slug: 'written-communication', level: 'EXPERT' },
    ],
    provenSimulations: [{ slug: 'written-communication-brief', score: 89 }],
  },
  {
    fullName: 'Ali Mohamed',
    email: 'ali.mohamed@demo.kazios.co.ke',
    phone: '+254712000008',
    county: 'Garissa',
    town: 'Garissa Town',
    ageBracket: '25-34',
    education: 'CERTIFICATE',
    yearsExperience: 2,
    employmentStatus: 'UNEMPLOYED',
    languages: ['en', 'sw', 'so'],
    headline: 'Data annotation and transcription, Somali and English',
    summary:
      'I have done annotation work for two AI projects, labelling text in Somali and English. Careful and consistent, and I follow guidelines exactly.',
    interests: ['data', 'languages', 'remote work'],
    hasLaptop: true,
    internetAccess: 'MOBILE_DATA',
    desiredIncomeKes: 32_000,
    workArrangement: 'REMOTE',
    preferredWorkTypes: ['GIG', 'CONTRACT', 'PART_TIME'],
    skills: [
      { slug: 'data-annotation', level: 'ADVANCED' },
      { slug: 'transcription', level: 'INTERMEDIATE' },
      { slug: 'quality-assurance', level: 'INTERMEDIATE' },
      { slug: 'attention-to-detail', level: 'ADVANCED' },
    ],
    provenSimulations: [{ slug: 'data-classification', score: 93 }],
  },
  {
    fullName: 'Janet Nyambura',
    email: 'janet.nyambura@demo.kazios.co.ke',
    phone: '+254712000009',
    county: 'Nakuru',
    town: 'Nakuru Town',
    ageBracket: '35-44',
    education: 'BACHELORS',
    fieldOfStudy: 'Human Resource Management',
    yearsExperience: 8,
    employmentStatus: 'UNEMPLOYED',
    languages: ['en', 'sw', 'ki'],
    headline: 'HR and operations administrator, eight years',
    summary:
      'Ran HR admin and office operations for a 40-person company until it closed last year. Payroll, records, recruitment support, supplier coordination.',
    interests: ['human resources', 'administration', 'operations'],
    hasLaptop: true,
    internetAccess: 'BROADBAND',
    desiredIncomeKes: 70_000,
    workArrangement: 'HYBRID',
    preferredWorkTypes: ['FULL_TIME', 'CONTRACT'],
    skills: [
      { slug: 'operations-admin', level: 'ADVANCED' },
      { slug: 'payroll', level: 'INTERMEDIATE' },
      { slug: 'document-preparation', level: 'ADVANCED' },
      { slug: 'project-coordination', level: 'INTERMEDIATE' },
      { slug: 'excel', level: 'INTERMEDIATE' },
    ],
  },
  {
    fullName: 'Kevin Wafula',
    email: 'kevin.wafula@demo.kazios.co.ke',
    phone: '+254712000010',
    county: 'Bungoma',
    town: 'Bungoma Town',
    ageBracket: '18-24',
    education: 'DIPLOMA',
    fieldOfStudy: 'Graphic Design',
    yearsExperience: 2,
    employmentStatus: 'SELF_EMPLOYED',
    languages: ['en', 'sw'],
    headline: 'Graphic designer — posters, branding and social assets',
    summary:
      'I design for local businesses, churches and events. Comfortable in Canva, Photoshop and Illustrator. Looking for remote design work.',
    interests: ['design', 'branding', 'creative work'],
    hasLaptop: true,
    internetAccess: 'MOBILE_DATA',
    desiredIncomeKes: 38_000,
    workArrangement: 'REMOTE',
    preferredWorkTypes: ['GIG', 'CONTRACT', 'PART_TIME'],
    skills: [
      { slug: 'graphic-design', level: 'ADVANCED' },
      { slug: 'canva', level: 'EXPERT' },
      { slug: 'adobe-photoshop', level: 'INTERMEDIATE' },
      { slug: 'brand-identity', level: 'INTERMEDIATE' },
    ],
    provenSimulations: [{ slug: 'design-brief-response', score: 77 }],
  },
  {
    fullName: 'Lucy Moraa',
    email: 'lucy.moraa@demo.kazios.co.ke',
    phone: '+254712000011',
    county: 'Kisii',
    town: 'Kisii Town',
    ageBracket: '25-34',
    education: 'DIPLOMA',
    yearsExperience: 4,
    employmentStatus: 'EMPLOYED_PART_TIME',
    languages: ['en', 'sw', 'guz'],
    headline: 'Virtual assistant — inbox, scheduling and admin',
    summary:
      'I support two overseas clients with inbox management, scheduling and document preparation. I want a third client or a full-time remote role.',
    interests: ['virtual assistance', 'admin', 'remote work'],
    hasLaptop: true,
    internetAccess: 'BROADBAND',
    desiredIncomeKes: 55_000,
    workArrangement: 'REMOTE',
    preferredWorkTypes: ['PART_TIME', 'CONTRACT', 'FULL_TIME'],
    skills: [
      { slug: 'virtual-assistance', level: 'ADVANCED' },
      { slug: 'email-management', level: 'ADVANCED' },
      { slug: 'calendar-management', level: 'ADVANCED' },
      { slug: 'document-preparation', level: 'INTERMEDIATE' },
      { slug: 'time-management', level: 'ADVANCED' },
    ],
    provenSimulations: [
      { slug: 'va-inbox-triage', score: 87 },
      { slug: 'va-schedule-build', score: 81 },
    ],
  },
  {
    fullName: 'Samuel Kiprotich',
    email: 'samuel.kiprotich@demo.kazios.co.ke',
    phone: '+254712000012',
    county: 'Kericho',
    town: 'Kericho Town',
    ageBracket: '25-34',
    education: 'BACHELORS',
    fieldOfStudy: 'Agribusiness',
    yearsExperience: 3,
    employmentStatus: 'UNDEREMPLOYED',
    languages: ['en', 'sw'],
    headline: 'Sales and field work in agriculture inputs',
    summary:
      'I sell agricultural inputs to smallholder farmers across the South Rift. I know the customers, and I hit targets. Open to sales roles in other sectors too.',
    interests: ['sales', 'agriculture', 'field work'],
    hasLaptop: false,
    internetAccess: 'MOBILE_DATA',
    desiredIncomeKes: 45_000,
    workArrangement: 'ONSITE',
    preferredWorkTypes: ['FULL_TIME', 'CONTRACT'],
    skills: [
      { slug: 'sales', level: 'ADVANCED' },
      { slug: 'lead-generation', level: 'INTERMEDIATE' },
      { slug: 'objection-handling', level: 'INTERMEDIATE' },
      { slug: 'verbal-communication', level: 'ADVANCED' },
    ],
    provenSimulations: [{ slug: 'sales-objection', score: 80 }],
  },
  {
    fullName: 'Amina Yusuf',
    email: 'amina.yusuf@demo.kazios.co.ke',
    phone: '+254712000013',
    county: 'Nairobi',
    town: 'Eastleigh',
    ageBracket: '18-24',
    education: 'SECONDARY',
    yearsExperience: 1,
    employmentStatus: 'CASUAL_WORKER',
    languages: ['en', 'sw', 'so'],
    headline: 'Data entry and shop assistant, looking for remote work',
    summary:
      'I have done data entry for a small business and worked in a shop. I type fast and I am careful. I would like to work from home.',
    interests: ['data entry', 'remote work'],
    hasLaptop: false,
    internetAccess: 'MOBILE_DATA',
    desiredIncomeKes: 22_000,
    workArrangement: 'REMOTE',
    preferredWorkTypes: ['GIG', 'PART_TIME', 'CASUAL'],
    skills: [
      { slug: 'data-entry', level: 'INTERMEDIATE' },
      { slug: 'attention-to-detail', level: 'INTERMEDIATE' },
    ],
    openToDiscovery: true,
  },
  {
    fullName: 'Collins Ochieng',
    email: 'collins.ochieng@demo.kazios.co.ke',
    phone: '+254712000014',
    county: 'Siaya',
    town: 'Bondo',
    ageBracket: '25-34',
    education: 'DIPLOMA',
    fieldOfStudy: 'Computer Science',
    yearsExperience: 3,
    employmentStatus: 'UNEMPLOYED',
    languages: ['en', 'sw', 'luo'],
    headline: 'Web developer — WordPress, Shopify and landing pages',
    summary:
      'I build and maintain websites for small businesses. Fifteen sites shipped, mostly WordPress and Shopify.',
    interests: ['web development', 'ecommerce'],
    hasLaptop: true,
    internetAccess: 'MOBILE_DATA',
    desiredIncomeKes: 65_000,
    workArrangement: 'REMOTE',
    preferredWorkTypes: ['CONTRACT', 'GIG', 'FULL_TIME'],
    skills: [
      { slug: 'web-development', level: 'ADVANCED' },
      { slug: 'wordpress', level: 'ADVANCED' },
      { slug: 'shopify', level: 'INTERMEDIATE' },
      { slug: 'html-css', level: 'ADVANCED' },
      { slug: 'javascript', level: 'INTERMEDIATE' },
    ],
  },
  {
    fullName: 'Esther Muthoni',
    email: 'esther.muthoni@demo.kazios.co.ke',
    phone: '+254712000015',
    county: 'Nyeri',
    town: 'Nyeri Town',
    ageBracket: '45-54',
    education: 'CERTIFICATE',
    yearsExperience: 15,
    employmentStatus: 'SELF_EMPLOYED',
    languages: ['en', 'sw', 'ki'],
    headline: 'Bookkeeping and admin for small businesses',
    summary:
      'I have kept books for shops and small businesses in Nyeri for fifteen years. Manual ledgers and QuickBooks. I want to take on remote clients.',
    interests: ['bookkeeping', 'small business'],
    hasLaptop: true,
    internetAccess: 'BROADBAND',
    desiredIncomeKes: 42_000,
    workArrangement: 'REMOTE',
    preferredWorkTypes: ['PART_TIME', 'GIG', 'CONTRACT'],
    skills: [
      { slug: 'bookkeeping', level: 'EXPERT' },
      { slug: 'invoicing', level: 'ADVANCED' },
      { slug: 'quickbooks', level: 'INTERMEDIATE' },
      { slug: 'operations-admin', level: 'ADVANCED' },
    ],
    provenSimulations: [{ slug: 'book-transaction-classification', score: 88 }],
  },
  {
    fullName: 'Ibrahim Noor',
    email: 'ibrahim.noor@demo.kazios.co.ke',
    phone: '+254712000016',
    county: 'Wajir',
    town: 'Wajir Town',
    ageBracket: '25-34',
    education: 'BACHELORS',
    fieldOfStudy: 'Education',
    yearsExperience: 5,
    employmentStatus: 'EMPLOYED_FULL_TIME',
    languages: ['en', 'sw', 'so'],
    headline: 'Teacher looking for evening and weekend online tutoring',
    summary:
      'I teach secondary mathematics. I want online tutoring or content work in the evenings and at weekends.',
    interests: ['teaching', 'tutoring', 'education'],
    hasLaptop: true,
    internetAccess: 'MOBILE_DATA',
    desiredIncomeKes: 25_000,
    workArrangement: 'REMOTE',
    preferredWorkTypes: ['PART_TIME', 'GIG'],
    skills: [
      { slug: 'tutoring', level: 'ADVANCED' },
      { slug: 'training-delivery', level: 'INTERMEDIATE' },
      { slug: 'verbal-communication', level: 'ADVANCED' },
      { slug: 'written-communication', level: 'INTERMEDIATE' },
    ],
  },
  {
    fullName: 'Nancy Adhiambo',
    email: 'nancy.adhiambo@demo.kazios.co.ke',
    phone: '+254712000017',
    county: 'Homa Bay',
    town: 'Homa Bay Town',
    ageBracket: '18-24',
    education: 'CERTIFICATE',
    yearsExperience: 1,
    employmentStatus: 'UNEMPLOYED',
    languages: ['en', 'sw', 'luo'],
    headline: 'Customer support and telesales, ready to start immediately',
    summary:
      'I did six months in a call centre before it downsized. I am comfortable on the phone and I keep my records straight.',
    interests: ['customer service', 'call centre'],
    hasLaptop: false,
    internetAccess: 'MOBILE_DATA',
    desiredIncomeKes: 25_000,
    workArrangement: 'ANY',
    preferredWorkTypes: ['FULL_TIME', 'PART_TIME', 'CASUAL'],
    skills: [
      { slug: 'customer-support', level: 'INTERMEDIATE' },
      { slug: 'telesales', level: 'BEGINNER' },
      { slug: 'call-centre', level: 'INTERMEDIATE' },
      { slug: 'verbal-communication', level: 'INTERMEDIATE' },
    ],
    provenSimulations: [{ slug: 'cs-ticket-classification', score: 74 }],
  },
  {
    fullName: 'Victor Kariuki',
    email: 'victor.kariuki@demo.kazios.co.ke',
    phone: '+254712000018',
    county: 'Nairobi',
    town: 'Westlands',
    ageBracket: '25-34',
    education: 'BACHELORS',
    fieldOfStudy: 'Statistics',
    yearsExperience: 4,
    employmentStatus: 'EMPLOYED_FULL_TIME',
    languages: ['en', 'sw'],
    headline: 'Data analyst — SQL, dashboards and reporting',
    summary:
      'I build reports and dashboards for a fintech. Looking for weekend project work in data analysis.',
    interests: ['data analysis', 'dashboards', 'fintech'],
    hasLaptop: true,
    internetAccess: 'BROADBAND',
    desiredIncomeKes: 90_000,
    workArrangement: 'REMOTE',
    preferredWorkTypes: ['GIG', 'CONTRACT', 'PART_TIME'],
    skills: [
      { slug: 'data-analysis', level: 'ADVANCED' },
      { slug: 'sql', level: 'ADVANCED' },
      { slug: 'excel', level: 'EXPERT' },
      { slug: 'data-visualisation', level: 'INTERMEDIATE' },
    ],
    provenSimulations: [{ slug: 'data-error-detection', score: 92 }],
  },
  {
    fullName: 'Rose Cherono',
    email: 'rose.cherono@demo.kazios.co.ke',
    phone: '+254712000019',
    county: 'Bomet',
    town: 'Bomet Town',
    ageBracket: '25-34',
    education: 'SECONDARY',
    yearsExperience: 6,
    employmentStatus: 'UNDEREMPLOYED',
    languages: ['en', 'sw'],
    headline: 'Retail supervisor moving into remote customer support',
    summary:
      'Six years supervising a retail shop — staff rotas, stock, complaints, daily banking. I want to move into remote support work.',
    interests: ['customer service', 'operations', 'remote work'],
    hasLaptop: false,
    internetAccess: 'MOBILE_DATA',
    desiredIncomeKes: 33_000,
    workArrangement: 'ANY',
    preferredWorkTypes: ['FULL_TIME', 'CONTRACT'],
    skills: [
      { slug: 'customer-support', level: 'INTERMEDIATE' },
      { slug: 'complaint-handling', level: 'ADVANCED' },
      { slug: 'inventory-management', level: 'ADVANCED' },
      { slug: 'teamwork', level: 'ADVANCED' },
    ],
    openToDiscovery: true,
  },
  {
    fullName: 'Joseph Mwangi',
    email: 'joseph.mwangi@demo.kazios.co.ke',
    phone: '+254712000020',
    county: 'Murang’a',
    town: 'Murang’a Town',
    ageBracket: '35-44',
    education: 'DIPLOMA',
    fieldOfStudy: 'Sales and Marketing',
    yearsExperience: 10,
    employmentStatus: 'UNEMPLOYED',
    languages: ['en', 'sw', 'ki'],
    headline: 'Business development — ten years selling to SMEs',
    summary:
      'A decade opening accounts with small and medium businesses across Central Kenya. I build pipelines from nothing and I close.',
    interests: ['sales', 'business development'],
    hasLaptop: true,
    internetAccess: 'BROADBAND',
    desiredIncomeKes: 80_000,
    workArrangement: 'HYBRID',
    preferredWorkTypes: ['FULL_TIME', 'CONTRACT'],
    skills: [
      { slug: 'sales', level: 'EXPERT' },
      { slug: 'lead-generation', level: 'ADVANCED' },
      { slug: 'cold-outreach', level: 'ADVANCED' },
      { slug: 'crm-management', level: 'INTERMEDIATE' },
      { slug: 'objection-handling', level: 'ADVANCED' },
    ],
    provenSimulations: [
      { slug: 'sales-lead-qualification', score: 85 },
      { slug: 'sales-outreach', score: 78 },
    ],
  },
];
